export const FETCH_USER_DETAULS_REQUEST = 'FETCH_USER_DETAULS_REQUEST'
export const FETCH_USER_DETAULS_SUCCESS = 'FETCH_USER_DETAULS_SUCCESS'
export const FETCH_USER_DETAULS_FAILURE = 'FETCH_USER_DETAULS_FAILURE'

